extern const GeoLayout castle_grounds_area_1_geo[];
extern const GeoLayout castle_grounds_area_1[];
extern const Collision castle_grounds_area_1_collision[];
extern const MacroObject castle_grounds_area_1_macro_objs[];
extern Vtx castle_grounds_dl_Mirror_Frame_mesh_vtx_0[64];
extern Gfx castle_grounds_dl_Mirror_Frame_mesh_tri_0[];
extern Vtx castle_grounds_dl_Mirror_Wall_mesh_vtx_0[4];
extern Gfx castle_grounds_dl_Mirror_Wall_mesh_tri_0[];
extern Vtx castle_grounds_dl_Mirrored_Small_Mirror_mesh_vtx_0[40];
extern Gfx castle_grounds_dl_Mirrored_Small_Mirror_mesh_tri_0[];
extern Vtx castle_grounds_dl_Mirrored_Small_Mirror_mesh_vtx_1[4];
extern Gfx castle_grounds_dl_Mirrored_Small_Mirror_mesh_tri_1[];
extern Vtx castle_grounds_dl_Mirrored_Table_Render_mesh_vtx_0[88];
extern Gfx castle_grounds_dl_Mirrored_Table_Render_mesh_tri_0[];
extern Vtx castle_grounds_dl_Mirrored_Window_mesh_vtx_0[4];
extern Gfx castle_grounds_dl_Mirrored_Window_mesh_tri_0[];
extern Vtx castle_grounds_dl_Room_mesh_vtx_0[38];
extern Gfx castle_grounds_dl_Room_mesh_tri_0[];
extern Vtx castle_grounds_dl_Room_mesh_vtx_1[96];
extern Gfx castle_grounds_dl_Room_mesh_tri_1[];
extern Vtx castle_grounds_dl_Small_Mirror_mesh_vtx_0[40];
extern Gfx castle_grounds_dl_Small_Mirror_mesh_tri_0[];
extern Vtx castle_grounds_dl_Small_Mirror_mesh_vtx_1[4];
extern Gfx castle_grounds_dl_Small_Mirror_mesh_tri_1[];
extern Vtx castle_grounds_dl_Table_Render_mesh_vtx_0[88];
extern Gfx castle_grounds_dl_Table_Render_mesh_tri_0[];
extern Vtx castle_grounds_dl_Window_mesh_vtx_0[4];
extern Gfx castle_grounds_dl_Window_mesh_tri_0[];

extern Gfx castle_grounds_dl_Mirror_Frame_mesh[];
extern Gfx castle_grounds_dl_Mirror_Wall_mesh[];
extern Gfx castle_grounds_dl_Mirrored_Small_Mirror_mesh[];
extern Gfx castle_grounds_dl_Mirrored_Table_Render_mesh[];
extern Gfx castle_grounds_dl_Mirrored_Window_mesh[];
extern Gfx castle_grounds_dl_Room_mesh[];
extern Gfx castle_grounds_dl_Small_Mirror_mesh[];
extern Gfx castle_grounds_dl_Table_Render_mesh[];
extern Gfx castle_grounds_dl_Window_mesh[];
extern Gfx castle_grounds_dl_material_revert_render_settings[];

