extern const GeoLayout bob_area_1_geo[];
extern const GeoLayout bob_area_1[];
extern const Collision bob_area_1_collision[];
extern const MacroObject bob_area_1_macro_objs[];
extern const GeoLayout bob_area_2_geo[];
extern const GeoLayout bob_dl_1___Main_Room_geo[];
extern const GeoLayout bob_dl_Left_Room_1_geo[];
extern const GeoLayout bob_dl_Left_Room_3_geo[];
extern const GeoLayout bob_dl_Right_Room_2_geo[];
extern const GeoLayout bob_area_2[];
extern const Collision bob_area_2_collision[];
extern const u8 bob_area_2_collision_rooms[];
extern const MacroObject bob_area_2_macro_objs[];
extern Vtx bob_dl_Tall_Grass_mesh_vtx_0[3];
extern Gfx bob_dl_Tall_Grass_mesh_tri_0[];
extern Vtx bob_dl_0_mesh_vtx_0[585];
extern Gfx bob_dl_0_mesh_tri_0[];
extern Vtx bob_dl_Minus_1_X_mesh_vtx_0[585];
extern Gfx bob_dl_Minus_1_X_mesh_tri_0[];
extern Vtx bob_dl_Minus_1_X_Minus_1_Z_mesh_vtx_0[585];
extern Gfx bob_dl_Minus_1_X_Minus_1_Z_mesh_tri_0[];
extern Vtx bob_dl_Minus_1_X_Minus_2_Z_mesh_vtx_0[294];
extern Gfx bob_dl_Minus_1_X_Minus_2_Z_mesh_tri_0[];
extern Vtx bob_dl_Minus_1_X_Plus_1_Z_mesh_vtx_0[585];
extern Gfx bob_dl_Minus_1_X_Plus_1_Z_mesh_tri_0[];
extern Vtx bob_dl_Minus_1_X_Plus_2_Z_mesh_vtx_0[294];
extern Gfx bob_dl_Minus_1_X_Plus_2_Z_mesh_tri_0[];
extern Vtx bob_dl_Minus_1_Z_mesh_vtx_0[585];
extern Gfx bob_dl_Minus_1_Z_mesh_tri_0[];
extern Vtx bob_dl_Minus_2_X_mesh_vtx_0[294];
extern Gfx bob_dl_Minus_2_X_mesh_tri_0[];
extern Vtx bob_dl_Minus_2_X_Minus_1_Z_mesh_vtx_0[294];
extern Gfx bob_dl_Minus_2_X_Minus_1_Z_mesh_tri_0[];
extern Vtx bob_dl_Minus_2_X_Minus_2_Z_mesh_vtx_0[143];
extern Gfx bob_dl_Minus_2_X_Minus_2_Z_mesh_tri_0[];
extern Vtx bob_dl_Minus_2_X_Plus_1_Z_mesh_vtx_0[294];
extern Gfx bob_dl_Minus_2_X_Plus_1_Z_mesh_tri_0[];
extern Vtx bob_dl_Minus_2_X_Plus_2_Z_mesh_vtx_0[143];
extern Gfx bob_dl_Minus_2_X_Plus_2_Z_mesh_tri_0[];
extern Vtx bob_dl_Minus_2_Z_mesh_vtx_0[294];
extern Gfx bob_dl_Minus_2_Z_mesh_tri_0[];
extern Vtx bob_dl_Plus_1_X_mesh_vtx_0[585];
extern Gfx bob_dl_Plus_1_X_mesh_tri_0[];
extern Vtx bob_dl_Plus_1_X_Minus_1_Z_mesh_vtx_0[585];
extern Gfx bob_dl_Plus_1_X_Minus_1_Z_mesh_tri_0[];
extern Vtx bob_dl_Plus_1_X_Minus_2_Z_mesh_vtx_0[294];
extern Gfx bob_dl_Plus_1_X_Minus_2_Z_mesh_tri_0[];
extern Vtx bob_dl_Plus_1_X_Plus_1_Z_mesh_vtx_0[585];
extern Gfx bob_dl_Plus_1_X_Plus_1_Z_mesh_tri_0[];
extern Vtx bob_dl_Plus_1_X_Plus_2_Z_mesh_vtx_0[294];
extern Gfx bob_dl_Plus_1_X_Plus_2_Z_mesh_tri_0[];
extern Vtx bob_dl_Plus_1_Z_mesh_vtx_0[575];
extern Gfx bob_dl_Plus_1_Z_mesh_tri_0[];
extern Vtx bob_dl_Plus_1_Z_mesh_vtx_1[45];
extern Gfx bob_dl_Plus_1_Z_mesh_tri_1[];
extern Vtx bob_dl_Plus_2_X_mesh_vtx_0[294];
extern Gfx bob_dl_Plus_2_X_mesh_tri_0[];
extern Vtx bob_dl_Plus_2_X_Minus_1_Z_mesh_vtx_0[294];
extern Gfx bob_dl_Plus_2_X_Minus_1_Z_mesh_tri_0[];
extern Vtx bob_dl_Plus_2_X_Minus_2_Z_mesh_vtx_0[143];
extern Gfx bob_dl_Plus_2_X_Minus_2_Z_mesh_tri_0[];
extern Vtx bob_dl_Plus_2_X_Plus_1_Z_mesh_vtx_0[294];
extern Gfx bob_dl_Plus_2_X_Plus_1_Z_mesh_tri_0[];
extern Vtx bob_dl_Plus_2_X_Plus_2_Z_mesh_vtx_0[143];
extern Gfx bob_dl_Plus_2_X_Plus_2_Z_mesh_tri_0[];
extern Vtx bob_dl_Plus_2_Z_mesh_vtx_0[294];
extern Gfx bob_dl_Plus_2_Z_mesh_tri_0[];
extern Vtx bob_dl_Tunnel_mesh_vtx_0[54];
extern Gfx bob_dl_Tunnel_mesh_tri_0[];
extern Vtx bob_dl_Tunnel_mesh_vtx_1[56];
extern Gfx bob_dl_Tunnel_mesh_tri_1[];
extern Vtx bob_dl_Tunnel_mesh_vtx_2[4];
extern Gfx bob_dl_Tunnel_mesh_tri_2[];
extern Vtx bob_dl_Left_Room_1_Mesh_mesh_vtx_0[26];
extern Gfx bob_dl_Left_Room_1_Mesh_mesh_tri_0[];
extern Vtx bob_dl_Left_Room_1_Mesh_mesh_vtx_1[4];
extern Gfx bob_dl_Left_Room_1_Mesh_mesh_tri_1[];
extern Vtx bob_dl_Left_Room_3_Mesh_mesh_vtx_0[26];
extern Gfx bob_dl_Left_Room_3_Mesh_mesh_tri_0[];
extern Vtx bob_dl_Left_Room_3_Mesh_mesh_vtx_1[4];
extern Gfx bob_dl_Left_Room_3_Mesh_mesh_tri_1[];
extern Vtx bob_dl_Right_Room_2_Mesh_mesh_vtx_0[26];
extern Gfx bob_dl_Right_Room_2_Mesh_mesh_tri_0[];
extern Vtx bob_dl_Right_Room_2_Mesh_mesh_vtx_1[4];
extern Gfx bob_dl_Right_Room_2_Mesh_mesh_tri_1[];

extern Gfx bob_dl_Tall_Grass_mesh[];
extern Gfx bob_dl_0_mesh[];
extern Gfx bob_dl_Minus_1_X_mesh[];
extern Gfx bob_dl_Minus_1_X_Minus_1_Z_mesh[];
extern Gfx bob_dl_Minus_1_X_Minus_2_Z_mesh[];
extern Gfx bob_dl_Minus_1_X_Plus_1_Z_mesh[];
extern Gfx bob_dl_Minus_1_X_Plus_2_Z_mesh[];
extern Gfx bob_dl_Minus_1_Z_mesh[];
extern Gfx bob_dl_Minus_2_X_mesh[];
extern Gfx bob_dl_Minus_2_X_Minus_1_Z_mesh[];
extern Gfx bob_dl_Minus_2_X_Minus_2_Z_mesh[];
extern Gfx bob_dl_Minus_2_X_Plus_1_Z_mesh[];
extern Gfx bob_dl_Minus_2_X_Plus_2_Z_mesh[];
extern Gfx bob_dl_Minus_2_Z_mesh[];
extern Gfx bob_dl_Plus_1_X_mesh[];
extern Gfx bob_dl_Plus_1_X_Minus_1_Z_mesh[];
extern Gfx bob_dl_Plus_1_X_Minus_2_Z_mesh[];
extern Gfx bob_dl_Plus_1_X_Plus_1_Z_mesh[];
extern Gfx bob_dl_Plus_1_X_Plus_2_Z_mesh[];
extern Gfx bob_dl_Plus_1_Z_mesh[];
extern Gfx bob_dl_Plus_2_X_mesh[];
extern Gfx bob_dl_Plus_2_X_Minus_1_Z_mesh[];
extern Gfx bob_dl_Plus_2_X_Minus_2_Z_mesh[];
extern Gfx bob_dl_Plus_2_X_Plus_1_Z_mesh[];
extern Gfx bob_dl_Plus_2_X_Plus_2_Z_mesh[];
extern Gfx bob_dl_Plus_2_Z_mesh[];
extern Gfx bob_dl_Tunnel_mesh[];
extern Gfx bob_dl_Left_Room_1_Mesh_mesh[];
extern Gfx bob_dl_Left_Room_3_Mesh_mesh[];
extern Gfx bob_dl_Right_Room_2_Mesh_mesh[];
extern Gfx bob_dl_material_revert_render_settings[];

